export const REQUEST_FETCH_DOMAIN = 'REQUEST_FETCH_DOMAIN';
export const FINISH_FETCH_DOMAIN = 'FINISH_FETCH_DOMAIN';
export const REQUEST_FETCH_LOCATION = 'REQUEST_FETCH_LOCATION';
export const FINISH_FETCH_LOCATION = 'FINISH_FETCH_LOCATION';