/**
 * Created by yangyang on 2017/6/28.
 */
export const REQUEST_FETCH_DOMAIN = 'REQUEST_FETCH_DOMAIN';
export const FINISH_FETCH_DOMAIN = 'FINISH_FETCH_DOMAIN';
export const REQUEST_FETCH_POSITION = 'REQUEST_FETCH_POSITION';
export const FINISH_FETCH_POSITION = 'FINISH_FETCH_POSITION';